### ISSUE TITLE
Translation not working

### ISSUE THREAD

**Issue by kalymnred** [GPCsolutions/dolibarr-module-template#19]
Nice job!!
But i have an issue here..
I've created my module using your template but none of the translation files are loaded within the module's pages.. And the problem continues to occurs to several installations..
Thank you in advance.

**Comment by rdoursenaud** [comment]
Thanks :)

I can't reproduce.

What Dolibarr version are you using?
On which platform?

Make sure you use:
```php
// Load language files (once per file).
$langs->load('yourlangfile@yourmodulename');
```
and
```php
// Display a translated string.
echo $langs->trans("YourLangKeyword");
```
with a language file located at langs/[LANG_CODE]/yourlangfile.lang
```properties
YourLangKeyword = A translated string
```
You may  want to enable the debug log file and check if it displays any error.
See https://wiki.dolibarr.org/index.php/Module_Syslog_(developer) for more infos.

**Comment by kalymnred** [comment]
Well i downloaded your module template and checked it with dolibarr versions 3.9.2, 4.0 beta, 4.0.0 on Ubuntu 16.04.
It works perfectly out of the box but when i tried to rename the module lets say to myorder, create new langs file at langs/en_US/myorderlangs.lang, and load the languages file with $langs->load('myorderlangs@myorder') nothing happens..
The return code of the load method is 2..

This isn't the first time i using your template and already have 2 modules working like a charm! But this is the first time this bug occurs. I'm going to restart the whole project maybe is my fault somehow..

**Comment by kalymnred** [comment]
Well this is embarrassing..:P was an enconding issue with the translation file itself (copied it without noticing the format) and nothing to to with the module at all..
sorry for the inconvenience

**Comment by rdoursenaud** [comment]
No problem. Thanks for reporting back.
